### ISSUE TITLE
Delay in discovery on busy management groups

### ISSUE THREAD

**Issue by brandubh** [QuaeNocentDocent/OMS-ManagementPack#11]
In very busy management groups the discovery of azure automation accounts, backup vault or workspaces can be delayed, this happens if the discovery starts before the management group has a chance to calculate the group membership for tenants.

Log Name:      Operations Manager
Source:        Health Service Modules
Date:          3/16/2016 5:42:52 PM
Event ID:      22406
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A

Description:
The PowerShell script failed with below exception

System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Username' because it is an empty string.
   at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Type argumentType, Object parameterValue, Boolean recurseIntoCollections)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)

Script Name:    Get-OMSManagedSystems.ps1 

One or more workflows were affected by this.  

Workflow name: QND.OMS.Workspace.Discovery 
Instance name: Microsoft Azure Enterprise 
Instance ID: {790A50F8-6D09-704B-3EC7-78AD8561126F} 
Management group: Progel OSM

**Comment by brandubh** [comment]
Fixed in version 2.0
